<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251129093612 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, creation_date DATE NOT NULL, publication_status VARCHAR(255) NOT NULL, proposer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D70989512B36786B ON challenge (title)');
        $this->addSql('CREATE INDEX IDX_D7098951B13FA634 ON challenge (proposer_id)');
        $this->addSql('CREATE TABLE challenge_user (challenge_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (challenge_id, user_id))');
        $this->addSql('CREATE INDEX IDX_843CD1CF98A21AC6 ON challenge_user (challenge_id)');
        $this->addSql('CREATE INDEX IDX_843CD1CFA76ED395 ON challenge_user (user_id)');
        $this->addSql('CREATE TABLE challenge_quote (challenge_id INT NOT NULL, quote_id INT NOT NULL, PRIMARY KEY (challenge_id, quote_id))');
        $this->addSql('CREATE INDEX IDX_6FA342E698A21AC6 ON challenge_quote (challenge_id)');
        $this->addSql('CREATE INDEX IDX_6FA342E6DB805178 ON challenge_quote (quote_id)');
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, content TEXT DEFAULT NULL, moderation_status VARCHAR(255) DEFAULT NULL, author_id INT NOT NULL, feedback_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526CF675F31B ON comment (author_id)');
        $this->addSql('CREATE INDEX IDX_9474526CD249A887 ON comment (feedback_id)');
        $this->addSql('CREATE UNIQUE INDEX comments_user_feedback_date_idx ON comment (author_id, feedback_id, created_at)');
        $this->addSql('CREATE TABLE donation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, donation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount NUMERIC(10, 2) NOT NULL, public_display BOOLEAN DEFAULT NULL, donor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_31E581A03DD7B7A7 ON donation (donor_id)');
        $this->addSql('CREATE TABLE feedback (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, content TEXT DEFAULT NULL, is_helpful BOOLEAN DEFAULT NULL, author_id INT NOT NULL, challenge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2294458F675F31B ON feedback (author_id)');
        $this->addSql('CREATE INDEX IDX_D229445898A21AC6 ON feedback (challenge_id)');
        $this->addSql('CREATE UNIQUE INDEX feedbacks_user_challenge_date_idx ON feedback (author_id, challenge_id, created_at)');
        $this->addSql('CREATE TABLE fund_usage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usage_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usage_description TEXT NOT NULL, amount_used NUMERIC(10, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D4CE53EB1342561 ON fund_usage (usage_date)');
        $this->addSql('CREATE TABLE quote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quote_text TEXT NOT NULL, author VARCHAR(255) DEFAULT NULL, added_date DATE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B71CBF4A96CF84D ON quote (quote_text)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, registration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE challenge ADD CONSTRAINT FK_D7098951B13FA634 FOREIGN KEY (proposer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE challenge_user ADD CONSTRAINT FK_843CD1CF98A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE challenge_user ADD CONSTRAINT FK_843CD1CFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE challenge_quote ADD CONSTRAINT FK_6FA342E698A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE challenge_quote ADD CONSTRAINT FK_6FA342E6DB805178 FOREIGN KEY (quote_id) REFERENCES quote (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CD249A887 FOREIGN KEY (feedback_id) REFERENCES feedback (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE donation ADD CONSTRAINT FK_31E581A03DD7B7A7 FOREIGN KEY (donor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feedback ADD CONSTRAINT FK_D2294458F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feedback ADD CONSTRAINT FK_D229445898A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE challenge DROP CONSTRAINT FK_D7098951B13FA634');
        $this->addSql('ALTER TABLE challenge_user DROP CONSTRAINT FK_843CD1CF98A21AC6');
        $this->addSql('ALTER TABLE challenge_user DROP CONSTRAINT FK_843CD1CFA76ED395');
        $this->addSql('ALTER TABLE challenge_quote DROP CONSTRAINT FK_6FA342E698A21AC6');
        $this->addSql('ALTER TABLE challenge_quote DROP CONSTRAINT FK_6FA342E6DB805178');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CF675F31B');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CD249A887');
        $this->addSql('ALTER TABLE donation DROP CONSTRAINT FK_31E581A03DD7B7A7');
        $this->addSql('ALTER TABLE feedback DROP CONSTRAINT FK_D2294458F675F31B');
        $this->addSql('ALTER TABLE feedback DROP CONSTRAINT FK_D229445898A21AC6');
        $this->addSql('DROP TABLE challenge');
        $this->addSql('DROP TABLE challenge_user');
        $this->addSql('DROP TABLE challenge_quote');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE donation');
        $this->addSql('DROP TABLE feedback');
        $this->addSql('DROP TABLE fund_usage');
        $this->addSql('DROP TABLE quote');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
